FRONTIER_WEBSITE_BASE_URL = (
    "https://elitedangerous-website-backend-production.elitedangerous.com"
)
FRONTIER_WEBSITE_API = f"{FRONTIER_WEBSITE_BASE_URL}/api"

SHIPS_FRONTIER_API_MAPPING = {
    "adder": "Adder",
    "alliance-challenger": "Alliance Challenger",
    "alliance-chieftain": "Alliance Chieftain",
    "alliance-crusader": "Alliance Crusader",
    "anaconda": "Anaconda",
    "asp-explorer": "Asp Explorer",
    "asp-scout": "Asp Scout",
    "beluga-liner": "Beluga Liner",
    "cobra-mk-iii": "Cobra MkIII",
    "cobra-mk-iv": "Cobra MkIV",
    "diamondback-explorer": "Diamondback Explorer",
    "diamondback-scout": "Diamondback Scout",
    "dolphin": "Dolphin",
    "eagle": "Eagle",
    "federal-assault-ship": "Federal Assault Ship",
    "federal-corvette": "Federal Corvette",
    "federal-dropship": "Federal Dropship",
    "federal-gunship": "Federal Gunship",
    "fer-de-lance": "Fer-de-Lance",
    "hauler": "Hauler",
    "imperial-clipper": "Imperial Clipper",
    "imperial-courier": "Imperial Courier",
    "imperial-cutter": "Imperial Cutter",
    "imperial-eagle": "Imperial Eagle",
    "keelback": "Keelback",
    "krait-mk-ii": "Krait MkII",
    "krait-phantom": "Krait Phantom",
    "mamba": "Mamba",
    "orca": "Orca",
    "python": "Python",
    "sidewinder": "Sidewinder",
    "type-6": "Type-6 Transporter",
    "type-7": "Type-7 Transporter",
    "type-9": "Type-9 Heavy",
    "type-10": "Type-10 Defender",
    "viper-mk-iii": "Viper MkIII",
    "viper-mk-iv": "Viper MkIV",
    "vulture": "Vulture",
}
