image: debian/buster
packages:
  - gcc
  - clang
  - meson
  - dash
sources:
  - https://github.com/corenting/ed-api
packages:
  - make
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - wget
  - curl
  - llvm
  - libncurses5-dev
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libffi-dev
  - liblzma-dev
  - python-openssl
  - git
tasks:
  - setup-pyenv: |
      curl https://pyenv.run | bash
      pyenv install 3.8.2
  - setup-poetry:
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - format: |
      poetry run make format-check
triggers:
  - action: email
    condition: failure
    to: "<corenting@gmail.com>"
