from enum import Enum


class ShipModel(Enum):
    ADDER = "adder"
    ANACONDA = "anaconda"
    ASP = "asp"
    ASP_SCOUT = "asp_scout"
    BELUGALINER = "belugaliner"
    COBRAMKIII = "cobramkiii"
    COBRAMKIV = "cobramkiv"
    CUTTER = "cutter"
    DIAMONDBACK = "diamondback"
    DIAMONDBACKXL = "diamondbackxl"
    DOLPHIN = "dolphin"
    EAGLE = "eagle"
    EMPIRE_COURIER = "empire_courier"
    EMPIRE_EAGLE = "empire_eagle"
    EMPIRETRADER = "empiretrader"
    FEDDROPSHIP = "federation_dropship"
    FEDDROPSHIP_MKII = "federation_dropship_mkii"
    FEDERATION_CORVETTE = "federation_corvette"
    FEDERATION_GUNSHIP = "federation_gunship"
    FERDELANCE = "ferdelance"
    HAULER = "hauler"
    INDEPENDANT_TRADER = "independant_trader"
    KRAIT_LIGHT = "krait_light"
    KRAIT_MKII = "krait_mkii"
    MAMBA = "mamba"
    ORCA = "orca"
    PYTHON = "python"
    SIDEWINDER = "sidewinder"
    TYPE6 = "type6"
    TYPE7 = "type7"
    TYPE9 = "type9"
    TYPE9_MILITARY = "type9_military"
    TYPEX = "typex"
    TYPEX_2 = "typex_2"
    TYPEX_3 = "typex_3"
    VIPER = "viper"
    VIPER_MKIV = "viper_mkiv"
    VULTURE = "vulture"
